# Generated by Django 3.2.5 on 2021-07-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('live_demo_link', models.CharField(blank=True, max_length=200)),
                ('github_page_link', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('technologies', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
            ],
        ),
    ]
